# Generated by Django 6.0.3 on 2026-03-30 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_name", models.CharField(blank=True, max_length=100)),
                (
                    "major",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("CE", "Computer Engineering"),
                            ("EE", "Electrical Engineering"),
                            ("ME", "Mechanical Engineering"),
                            ("CI", "Computer Information Systems"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        choices=[
                            (2025, 2025),
                            (2026, 2026),
                            (2027, 2027),
                            (2028, 2028),
                            (2029, 2029),
                            (2030, 2030),
                        ]
                    ),
                ),
                ("current_classes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
