# Generated by Django 6.0.3 on 2026-03-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="graduation_year",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (2025, 2025),
                    (2026, 2026),
                    (2027, 2027),
                    (2028, 2028),
                    (2029, 2029),
                    (2030, 2030),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="major",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("CE", "Computer Engineering"),
                    ("EE", "Electrical Engineering"),
                    ("ME", "Mechanical Engineering"),
                    ("CI", "Computer Information Systems"),
                ],
                max_length=10,
            ),
        ),
    ]
