# Generated by Django 6.0.3 on 2026-05-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_graduation_year_alter_profile_major"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("08:00", "8:00 AM - 9:15 AM"),
                            ("09:30", "9:30 AM - 10:45 AM"),
                            ("11:00", "11:00 AM - 12:15 PM"),
                            ("12:30", "12:30 PM - 1:45 PM"),
                            ("14:00", "2:00 PM - 3:15 PM"),
                            ("15:30", "3:30 PM - 4:45 PM"),
                            ("17:00", "5:00 PM - 6:15 PM"),
                            ("18:30", "6:30 PM - 7:45 PM"),
                            ("19:00", "7:00 PM - 8:15 PM"),
                            ("20:00", "8:00 PM - 9:15 PM"),
                            ("21:30", "9:30 PM - 10:45 PM"),
                        ],
                        max_length=5,
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "day", "time_slot")},
            },
        ),
    ]
