# Generated by Django 6.0.3 on 2026-05-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_scheduleentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScheduleEntry",
        ),
    ]
