# Generated by Django 6.0.3 on 2026-05-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_scheduleentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hashtags",
            field=models.TextField(blank=True),
        ),
    ]
