# Generated by Django 6.0.3 on 2026-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="major",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("CE", "Computer Engineering"),
                    ("EE", "Electrical Engineering"),
                    ("ME", "Mechanical Engineering"),
                    ("CI", "Computer Information Systems"),
                    ("CV", "Civil Engineering"),
                    ("MF", "Manufacturing Engineering"),
                    ("CY", "Cyberspace & Informatics"),
                ],
                max_length=10,
            ),
        ),
    ]
