# Generated by Django 6.0.3 on 2026-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_profile_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
